framework:
  messenger:
    transports:
      async_priority_high:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          stream: 'high_priority'

    routing:
      'App\Message\Event\UserCreatedEvent': async_priority_high
