framework:
  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'

    # Here we define the routing
    routing:
      # Commands
      'App\Message\Event\UserCreatedEvent': async
